[package]
name = "schema"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "schema"
path = "src/main.rs"

[lib]
name = "blank_schema"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
kyyn-core = "=1.0.0-rc.7"
serde = { version = "1", features = ["derive"] }
ron = "0.12"
chrono = { version = "0.4", default-features = false, features = ["serde", "std"] }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
wit-bindgen = "=0.58.0"

[build-dependencies]
kyyn-schema-build = "=1.0.0-rc.7"

[workspace]
